### ISSUE TITLE
GraphQLServletListener cant be registered in OSGI

### ISSUE THREAD

**Issue by maarten-blokker** [graphql-java-kickstart/graphql-java-servlet#164]
Im trying to register a GraphQLServletListener so i can set some headers on the response. When i register a listener in OSGI, the following code should pick it up and add it to the configuration:

OsgiGraphQLHttpServlet.java
```
    @Reference(cardinality = ReferenceCardinality.MULTIPLE, policy = ReferencePolicy.DYNAMIC)
    public void bindServletListener(GraphQLServletListener listener) {
        this.addListener(listener);
    }
```

which then calls:

AbstractGraphQLHttpServlet 
```
    public void addListener(GraphQLServletListener servletListener) {
        configuration.add(servletListener);
    }
```

However, the configuration field is not initialised yet until the servlet gets registered. So an NPE is thrown.

graphql-java version: 11.0
graphql-java-servlet version: 7.3.3

**Comment by oliemansm** [comment]
Added a check and fix in 7.5.1.

**Comment by maarten-blokker** [comment]
I suppose the nullpointer does not occur anymore, but the exception was symptomatic of events not occurring in the right order. You will still be unable to register a GraphQLServletListener using OSGI.

**Comment by oliemansm** [comment]
Have you verified this with a local build after this change? Because with this fix the listener should be added to the configuration once that’s initialized.

Groeten,
Michiel
________________________________
Van: Maarten Blokker <notifications@github.com>
Verzonden: Saturday, June 22, 2019 10:53:25 AM
Aan: graphql-java-kickstart/graphql-java-servlet
CC: Michiel Oliemans; State change
Onderwerp: Re: [graphql-java-kickstart/graphql-java-servlet] GraphQLServletListener cant be registered in OSGI (#164)


I suppose the nullpointer does not occur anymore, but the exception was symptomatic of events not occurring in the right order. You will still be unable to register a GraphQLServletListener using OSGI.

**Comment by maarten-blokker** [comment]
I have not verified correct behaviour yet, just made the conclusion based of the changes im seeing. I'l try to run some local tests somewhere next weeks, thanks for the effort!
