### ISSUE TITLE
MismatchedInputException when running in WebLogic Server

### ISSUE THREAD

**Issue by markuslohn** [graphql-java-kickstart/graphql-java-servlet#170]
I am running the GraphQLHttpServlet with a simple example in Oracle WebLogic Server (example attached as file). When I post a request to the server with the following command:

curl -X POST -H "Content-Type: application/json" --data '{ "query": "{ hello }" }' http://localhost:7001/graphql-db-test/graphql

I always got the following exception:

2019-04-26 07:53:05,754- Bad POST request: parsing failed - graphql.servlet.AbstractGraphQLHttpServlet(216)
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (weblogic.servlet.internal.ServletInputStreamImpl); line: 1, column: 0]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1356)
        at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:358)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1596)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1188)
        at graphql.servlet.GraphQLObjectMapper.readGraphQLRequest(GraphQLObjectMapper.java:65)
        at graphql.servlet.AbstractGraphQLHttpServlet.lambda$init$4(AbstractGraphQLHttpServlet.java:212)
        at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:309)
        at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:300)
        at graphql.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:330)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
![Screenshot 2019-04-26 at 12 51 50](https://user-images.githubusercontent.com/25202280/56803100-16128500-6822-11e9-9ff1-5395f68f09f8.png)

I found that the ServletInputStream will be read two times. First to detect a batched query and second by the Jackson library to parse the JSON request. The second read with Jackson always return null for the InputStream. 

It seems that the InputStream can't read multiple times in an application server environment. 

As a workaround I implemented a HttpServletRequestWrapper and overrides getInputStream. This solutions works. 

However is this a bug in the implementation of the GraphQLServlet? In the isBinaryQuery method the InputStream will only be marked and resetted.

**Comment by oliemansm** [comment]
Yeah, that's something we need to fix. Thanks for the detailed report.

**Comment by oliemansm** [comment]
I was taking a closer look at this one. Before the method [isBatchedQuery(InputStream)](https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/373869b773bf280c1d745d8deb77665defd84929/src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java#L455) is called, it always calls [asMarkableInputStream](https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/373869b773bf280c1d745d8deb77665defd84929/src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java#L247) which wraps it in a `BufferedInputStream` providing `mark` and `reset` to it.

So I don't quite follow why you would then run into this problem actually, because by the looks of that `isBatchedQuery` method it does call reset at the correct times.

Are you able to identify more clearly what's going and what's solved by your wrapper? Because by the looks of it, you shouldn't need it.

**Comment by markuslohn** [comment]
Hi,

the only thing I can say is that the InputStream isn't usable more than one time in WebLogic Server. Also call mark and reset doesn't affect this behaviour in WebLogic Server. So the workaround I used cached the content of the stream with the first read. Afterwards every time getInputStream is called a new InputStream is created based on the cached content. So the exception is gone. There exists the possibility that this issue is only WebLogic related. However I didn't executed my example in other application servers, like Tomcat...

Regards

Markus

**Comment by oliemansm** [comment]
That sounds like in that process `httpServletRequest.getInputStream()` is called at least twice, instead of calling it once and using mark and reset. Correct? You don't have any debugging information about where it is called the second time by any chance?

**Comment by markuslohn** [comment]
The graphql-servlet call it twice a time. The first time the InputStream is read to identify whether it is a batch request. The second time is the real processing of the InputStream.

**Comment by jyangtj** [comment]
I am having the exact same issue with Weblogic 12.2.1.3.0 and GraphQL Java Servlet 7.3.3.  It looks that weblogic.servlet.internal.ServletInputStreamImpl does not handle mark and reset correctly.  Thanks for the information posted here, I can work around with this now.

**Comment by oliemansm** [comment]
The only reason this mark and reset stuff is happening is to be able to determine if it's a batched query. Which has been deprecated for a while now in favor of data loaders. So instead of trying to fix this I think we should remove support for batched queries entirely which will fix this issue as a nice side effect.

**Comment by markuslohn** [comment]
Seems also be a valid solution for me.

**Comment by oliemansm** [comment]
I just noticed I removed this resetting of the input stream in version 9.0.0 already. So it already shouldn't be a problem anymore.
