### ISSUE TITLE
What's the difference between PerQueryBatchedInvocationInput and PerRequestBatchedInvocationInput?

### ISSUE THREAD

**Issue by mxmlnglt** [graphql-java-kickstart/graphql-java-servlet#211]
Hello,

I don't see the point of having these 2 classes, because they basically do the same thing:
 * [PerQueryBatchedInvocationInput](../blob/master/src/main/java/graphql/servlet/input/PerQueryBatchedInvocationInput.java)
 * [PerRequestBatchedInvocationInput](../blob/master/src/main/java/graphql/servlet/input/PerRequestBatchedInvocationInput.java)

**Comment by jmccaull** [comment]
There are subtle differences in how the context is supplied to each one. Depending on which context you select, the per query input will call the supplier for each input, where as the per request will call it once and provide the same context to each input.
The changes were made to align with Apollo's link module, https://www.apollographql.com/docs/link/links/batch-http/ see the section on context. I agree that having two different uses of the same supplier probably isn't optimal because it requires implementations to possibly anticipate which way they will be used. This logic specifically was broken out into an abstraction because otherwise it would require the enum to be passed around and lead to higher potential for inconsistency. There is potential for improvement/refactor here but it would touch a lot of the code base I think.

**Comment by oliemansm** [comment]
@jmccaull Does the refactor in #217 open up possibilities to improve/refactor this part too?
