### ISSUE TITLE
Custom servlet listener with graphql-spring-boot-starter

### ISSUE THREAD

**Issue by PlayMa256** [graphql-java-kickstart/graphql-java-servlet#240]
Hello!

I'm using `graphql-spring-boot-starter` and i'm trying to add a custom sevlet to it but docs are a little missleading and i can't find the best place to put it! 

I just want to add custom info to the context! 

How could i do it! Thank you!

**Comment by oliemansm** [comment]
The subject and body of your question aren't very clear and seem to be asking different things. You mention that "you just want to add custom info to the context".

See #226 how to do that.

**Comment by PlayMa256** [comment]
So in graphql there is the concept of contexts, which can have any data on data, to be retrieved on any mutation or resolver. I was looking on how to do that!

**Comment by oliemansm** [comment]
Right, so that's why I pointed you to https://github.com/graphql-java-kickstart/graphql-java-servlet/issues/226#issuecomment-607408700. Did you take a look at that? The custom context class you define there can contain any properties you want to pass around and you can get a hold of it in resolvers by using the `DataFetchingEnvironment` which can exist as the last argument of any resolver method, i.e.:

```java
void myQueryMethod(int argOne, String argTwo, DataFetchingEnvironment env) {
  MyCustomContext context = (MyCustomContext) env.getContext();
  Thing myThing = context.getThing();
  
}
```

**Comment by oliemansm** [comment]
Can you confirm whether this answered your question so we can close the issue?

**Comment by oliemansm** [comment]
Closing the issue due to inactivity.
