### ISSUE TITLE
Request Timeout for malicious Graphql queries

### ISSUE THREAD

**Issue by Thinkenterprise** [graphql-java-kickstart/graphql-java-servlet#274]
To prevent malicious Graphql Queries, I would like to abort requests on the server that are too long. So I need a **request timeout**. There is no configuration for this in Java EE Servlet, right!? In Spring Boot you can e.g. configure ``server.connection-timeout``, which does not the same as a request timeout!! Would it be possible to provide an ``SimpleInstrumentation`` for example ``RequestTimeoutInstrumentation`` which implementation request timeout. I know that instrumentations like ``MaxQueryComplexityInstrumentation`` already exist for **other** types of malicious Graphql Queries. In this context, another instrumentation for throttling like ``ThrottlingInstrumentation``would be conceivable and would round off the DDOS topic very nicely. From my point of view, these are important points, or should infrastructure do that? https://www.howtographql.com/advanced/4-security/

**Comment by oliemansm** [comment]
A quick Google search led me to [this StackOverflow issue](https://stackoverflow.com/questions/52098798/best-way-to-limit-time-execution-in-a-restcontroller/52098799) suggesting a solution for a regular Spring Boot `@RestController`. So it looks like Spring doesn't provide anything out of the box for it.

Maybe instead of `RequestTimeoutInstrumentation` it shouldn't be named in line with HTTP, but more in line with GraphQL, e.g. `MaxExecutionTimeInstrumentation`. Ideally this would then be part of the core [graphql-java](https://github.com/graphql-java/graphql-java) project instead of here. Could you raise the issue there to see if they're willing to include something like this?
