### ISSUE TITLE
A way to send an 401 - Unauthorized HTTP response

### ISSUE THREAD

**Issue by DavidFlorin** [graphql-java-kickstart/graphql-java-servlet#49]
I want to use the GraphQL for authentication mechanism also, using mutations

I was following the [How to GraphQL - Backend Java tutorial](https://www.howtographql.com/graphql-java/5-authentication/) and in the `createContext` method:

```java
@Override
protected GraphQLContext createContext(Optional<HttpServletRequest> request, Optional<HttpServletResponse> response) {
// ...
}
```
* I need to be able to check the token (it may be expired or a wrong token provided) and return a custom status code, like `401 - Unauthorized` so we can redirect the user in the web to a login page eventually. At the moment, if I throw an Exception in that method, I will get a `500 - Server Error` and this is not explicit enough. Is there any way to do that?

* How can I check the mutation name in order to exclude `signin` calls or some public mutations (mutations calls that does not require an `Authorization` header)

**Comment by apottere** [comment]
The general way for doing authentication/authorization with graphql is to do authentication at the transport layer and authorization at the business logic layer.  With graphql-java-servlet, that usuall means

1. Authentication should be done in a servlet filter on the same path that graphql-java-servlet is registered on.  If unsuccessful, return a 401 from the filter.  If successful, pass the user object to the graphql context (if desired).  This can be done a number of ways, but setting a thread-local in the filter and reading it in `createContext` will work just fine (this is essentially what spring-security does).
2. Authorization should be done in the business logic layer, i.e. within your data fetchers.  Since graphql is generally transport-agnostic, the validation in your data fetchers shouldn't change the status code - the unauthorized error should be delivered in the "errors" object so the client can decide what to do about it.

In order to map a custom "unauthorized" exception in your data fetchers, you'll need to pass a `GraphQLErrorHandler` to the servlet that transforms that custom exception into an error the client understands.

**Comment by apottere** [comment]
If you don't need to enforce authentication at the graphql endpoint, which is the case if you're using graphql to sign in, you can skip the filter (`#1`).

**Comment by DavidFlorin** [comment]
Ok, I can use a filter to deal with requests with invalid tokens or no `Authorization` header but I really need to be able to check the mutation name so I can let the `signin` mutation to by-pass the token check. Can you give me a hint about how can I do that?

The `no filter` and `an anonymous user` in `createContext` is not an option because I need to reject any request that doesn't have a valid token (except the `signin` of course).

What I need basically is a way to `sign in` the user using a mutation and check for the Authorization header of all request (except the `sign in` one). I can use filters but I can not use other endpoints than `/graphql`. I need to be able to do that in order to use these `graphql` libs in my project.

**Comment by kaqqao** [comment]
Just a note, the tutorial on HowToGraphQL is woefully outdated :( I'll try to update it sometime soon but no hard promises...

As for authentication and authorization, if you need anything beyond the basics, you're much better off delegating it to Spring Security, as it allows you to deal with it declaratively.
As @apottere  said, you can do a similar thing yourself, though.
The way I'd maybe do it is:

1. Stuff the current user or the request object into the context
2. Create an instrumentation that will get the user/request from the context (`beginValidation` and `beginDataFetch` for example have access to the context) and check if the current operation is allowed for that user.
3. If not, throw an `AbortExecutionException`

The only other thing I can come up with is to have a check in each and every data fetcher... which is awful.

**Comment by oliemansm** [comment]
@DavidFlorin I'm assuming you were able to find a solution with the advice provided here?

**Comment by oliemansm** [comment]
Closing due to all the answers given. @DavidFlorin please feel free to reopen if you have any other questions.
