### ISSUE TITLE
Apollo keepalive incorrect implementation

### ISSUE THREAD

**Issue by rsredsq** [graphql-java-kickstart/graphql-java-servlet#91]
Hello!
The new subscription feature implementation is really good, unfortunately realisation of apollo protocol is not aligned with the specification.

In the specification said, that if server sends GQL_CONNECTION_KEEP_ALIVE once, then it should send it periodically. 
https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_keep_alive

Otherwise, client will close current connection and create new one each 30s(according to this logic https://github.com/apollographql/subscriptions-transport-ws/blob/f95a363fb63df014d16e1333e607fe92520ebfd1/src/client.ts#L515)
![image](https://user-images.githubusercontent.com/5163918/43363292-d41b4dce-9312-11e8-8b39-993982db136e.png)

So my proposal is to make it configurable. If keepalive is enabled, then it should be sent to client periodically(should be configurable in properties). If keepalive is disabled, then it shouldn't be send

Thanks

**Comment by oliemansm** [comment]
Hi, thanks for reporting it. Sounds like a proper solution.

**Comment by oliemansm** [comment]
@apottere What is the reason you've made that `subscriptionProtocolFactories` stuff `static`? Because that makes it a bit hard to make it configurable. I see we could pass this proposed setting along through the constructor of `GraphQLWebsocketServlet` together with the `SubscriptionHandlerInput`, but that would leak Apollo specific details.

If there's no specific reason then instead of keeping them `static` we could extract it in some kind of configurable `Provider`.

**Comment by oliemansm** [comment]
Nevermind, I've found a way around it by introducing the `ApolloSubscriptionConnectionListener` I needed for handling custom `onConnect` as described in #100.
